### ISSUE TITLE
0.4.0 doesn't compile with GHC <7.10

### ISSUE THREAD

**Issue by phadej** [MichaelXavier/cron#25]
... although advertised `tested-with` in the cabal file. (And bounds were allowing to build it).

```
src/System/Cron/Types.hs:153:55:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<>’ (imported from Data.Monoid)

src/System/Cron/Types.hs:374:63:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<>’ (imported from Data.Monoid)
```

Consider using `base-compat`.

**Comment by MichaelXavier** [comment]
This is resolved in master now and I'll be pushing 0.4.1 momentarily. Thanks.
