### PR TITLE
Fix build with ghc-8.8

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Looks like there's been some build failures. I think you need to import the module for it.

**Comment by hasufell** [comment]
```
/home/travis/build/MichaelXavier/cron/src/System/Cron/Internal/Describe/Options.hs:16:1: error: [-Wunused-imports, -Werror=unused-imports]
```
Not really an error...

**Comment by MichaelXavier** [comment]
The best way I've found to solve this is to `import Data.Semigroup as Semigroup` and then at 1 random use site that uses something from that module, use it qualified, e.g. `instance Semigroup.Semigroup`. For older compilers which need the explicit import, this works. For new compilers that don't need the import, the qualified import resolves this unused error, no CPP required. I'll go ahead and take care of that soon on master.
